fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    eyplib: "git://github.com/AtlasIT-AM/eyp-eyplib.git"
  symlinks:
    postgresql: "#{source_dir}"
