---
language: ruby
sudo: required
services:
  - docker
script:
  - bundle exec rspec spec/acceptance
bundler_args: --without system_tests
matrix:
  include:
  - rvm: default
    env: LINT=puppetcode
    dist: trusty
    bundler_args:
    script: bundle exec rake lint
  - rvm: default
    env: LINT=metadata
    dist: trusty
    bundler_args:
    script: bundle exec rake metadata_lint
  - rvm: default
    env: JOB=validate
    dist: trusty
    bundler_args:
    script: bundle exec rake validate
  - rvm: default
    env: BEAKER_set="centos6-docker" PG_VERSION="pg9"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/pg9*_spec.rb
  - rvm: default
    env: BEAKER_set="centos6-docker" PG_VERSION="pg10"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/pg1*_spec.rb
  - rvm: default
    env: BEAKER_set="centos7-docker" PG_VERSION="ALL"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/pg9*_spec.rb spec/acceptance/pg1*_spec.rb
